### ISSUE TITLE
Enhanced Production Levels

### ISSUE THREAD

**Issue by G-Wen** [spacechem-community-developers/SpaceChem-Community-Edition#10]
Currently the game offers fairly limited production level design tools. Each of the following constrains can be relaxed:
1.a Only 6 types of reactors to choose from.
   b. Quantum reactors and sandbox reactors are not available. 
2. Production levels are limited to only one random input.
3. The reactor quota is shared between all reactors. 
4. The reactor quota is bound between 2 and 6. 
5. Fixed reactors and pipes (Flidais production level)

The ability to design custom reactors (like research levels) would be very nice. This could include additional options such as having inputs / outputs disabled (like assembly/disassembly reactors) or walls such as quantum reactors.

**Comment by csaboka** [comment]
> The reactor quota is shared between all reactors.

The reactor quota is always shared between all reactors in the whole game. How would the UI even work if you had more complex rules than a global count limit?

**Comment by IQuick143** [comment]
I think the reactor choices and customisation are cool but I don't think a quota per reactor type would be any good except for some niche challenge levels since it heavily constraints players options and SC is an open-ended game after all.

**Comment by G-Wen** [comment]
![image](https://user-images.githubusercontent.com/1546652/61588483-188e2d80-ab38-11e9-9aab-2f388a6e0591.png)

Something like this to demonstrate a 6 sensor reactor quota / 5 super bonder quota. 

Also edited in the wish to create levels with fixed reactors and pipes as seen in the last two Flidais production levels.

**Comment by csaboka** [comment]
Everything but number 3 are now available with the new "free-form" production puzzle type of ResearchNet, released just now as part of CE v4.3.

Having different quotas per reactor type is a big enough task to warrant its own issue, and there doesn't seem to be agreement if it's a good idea at all. Feel free to re-open it as its own issue if you'd like, but I'm closing this one.
