### ISSUE TITLE
Doesn't launch on my system

### ISSUE THREAD

**Issue by GoiDcl** [spacechem-community-developers/SpaceChem-Community-Edition#102]
Some specifications from `System` page:
```
  Processor: AMD Ryzen 7 5700X 8-Core Processor 3.40 GHz
  Edition: Windows 10 Pro
  Version: 22H2
  OS build: 19045.3930
```
Tried to change compatibility of `SpaceChem.exe` file to every setting presented and `running as admin` option for no use
Please, help. What else can I show you in order to help you to find solution?

**Comment by csaboka** [comment]
Are you having issues with the vanilla game, or does this only happen if you select Community Edition in the Steam Beta tab? If it's the former, you should contact Zachtronics for troubleshooting, since this project is specifically for the Community Edition.

**Comment by GoiDcl** [comment]
You are right, forgot to mention the base game doesn't launch either

**Comment by csaboka** [comment]
In that case, as I mentioned above, please contact Zachtronics for support. This is just a fan project maintained by volunteers, we don't have the manpower to handle issues that are unrelated to Community Edition.

I'm closing this issue.
