### ISSUE TITLE
Duplicate level button to duplicate solution too

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#12]
Currently, it takes 1 click to create an empty copy of a selected puzzle (duplicate), and 2 clicks to create a copy of a puzzle + solution (export soln, import soln).
I claim that the latter use case is more common, and merits the Duplicate button duplicating both level + soln (1 click), relegating making a fresh puzzle copy to 2 clicks (export puzzle / import puzzle).

I would however accept if it's decided that original functionality shouldn't be changed just for this.

**Comment by csaboka** [comment]
Good suggestion! At the very least, it's worth to add an option to duplicate both the puzzle and the solution by default instead of just the puzzle.

**Comment by csaboka** [comment]
This should work in the next release. There will be an option in the settings, default off, that allows the Duplicate button to work as requested.
