### ISSUE TITLE
Customizable Production Level input rate

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#13]
A feature that would open up huge new realms of gameplay for the community would be the ability to specify in a production level's json a value other than 10 for the number of cycles between inputs (possibly even a custom input rate for each individual input).

I will go to war for this.

**Comment by csaboka** [comment]
This should be doable, but not in a backwards-compatible way. This means puzzles with custom input rates could only be loaded by the Community Edition. (The alternative is that the vanilla game could load them, but ignore the custom rates, which could cause all kinds of confusion.)

**Comment by csaboka** [comment]
This is now available as part of the "free-form" production puzzles introduced in CE v4.3. Once you place an input, you can edit not just the molecules generated, but also the output rate. You can specify 1 to make the input emit a molecule in every cycle, giving you almost the same behavior as research puzzles have (except that it will still take time for the molecules to traverse the pipe if the pipe is longer than 1 unit). You can also specify numbers larger than 10 to create inputs that are slower than usual.
