### ISSUE TITLE
Pass-through Output

### ISSUE THREAD

**Issue by G-Wen** [spacechem-community-developers/SpaceChem-Community-Edition#14]
Add a pass-through output component to custom edition production levels. 
A pass-through output is a pass-through printer which accepts only a predefined molecule and counts outputs.

**Comment by csaboka** [comment]
I think this shouldn't be too difficult to implement. Things to consider when using it in a puzzle:

* If the puzzle has a recycler, the player can connect the pass-through output to it and practically make it work like a regular output.
* If the number of required molecules is too low, you could use the "waste pipe" technique to still avoid further processing of molecules going through the pass-through output.

**Comment by G-Wen** [comment]
Another thing to consider: with pass-through outputs you can also pipe the output back into the input at the cost of roughly half a reactor.

**Comment by csaboka** [comment]
This is implemented in v4.4, released just now. I'm closing the ticket, but feel free to reopen or create a new one if you see any issues with it.
