### ISSUE TITLE
How to run this v4.4?

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#16]
I just copy exe file to specific folder on Mac, this is first to install community edition, but when I run SpaceChem from Sterm, it is still original version, what can I run the community edition?

**Comment by csaboka** [comment]
I'm sorry, I don't use Mac, so I don't know where the game folder is. The idea is that you need to find your original SpaceChem.exe file and replace it with ours. If you try to launch the exe file from any other folder, Steam will step in and launch the original one from the correct folder.

Once I can talk to someone who owns a Mac, I can give you more specific instructions. Until then, please try to locate the original SpaceChem.exe file yourself and make sure to overwrite it with the file downloaded from here.

**Comment by csaboka** [comment]
Here are some instructions from a Mac user who could get the game working:

> On Mac, the .exe file is within ~/Library/Application Support/Steam/steamapps/common/SpaceChem/SpaceChem.app.  In the Finder, right-click on SpaceChem.app and select Show Package Contents.  Then navigate to Contents/Resources/SpaceChem.exe.  (To display the ~/Library folder in the Finder, hold down the option key while viewing the Go menu and select Library.)

I hope this helps.

**Comment by mikezang** [comment]
I followed Installing the update in readme as below, can you modify it?
Mac: ~/Library/Application Support/Steam/steamapps/common/SpaceChem

Then can you tell me if I can buy the SpaceChem: 63 Corvi and use it with community edition?

**Comment by 12345ieee** [comment]
The CE is completely compatible with the 63 Corvi DLC, as soon as you buy it you'll be able to use it both with the CE and with the vanilla game.

**Comment by csaboka** [comment]
I've updated the Readme file, it should now be more helpful for Mac users.

I believe we've answered every question here, so I'm closing this ticket, but feel free to reopen if something is still not clear.

**Comment by mikezang** [comment]
There is no Mac in information about 63 Corvi DLC, is it no problems to played on Mac?
