### ISSUE TITLE
Mission to 17 molecules that changed the world

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#17]
Did anyone design user’s mission collect to produce real Molecular structural formula, like 17 molecules that changed the world as below:
①PENICILLIN — R-C9H11N2O4S
②SODIUM CHLORIDE — NaCl
③POTASSIUM NITRATE — KNO3
④ASPIRIN — C9H8O4
⑤SODIUM STEARATE — NaC18H35O2
⑥SILICON — Si
⑦RUBBER — C5H8
⑧SILICON DIOXIDE — SiO2
⑨POLYETHYLENE — (C2H4)N
⑩DDT — C14H9Cl5
⑪MORPHINE — C17H19NO3
⑫AMMONIA — NH3
⑬IRON — Fe
⑭ETHANOL — C2H6O
⑮SULFURIC ACID — H2SO4
⑯PROGESTIN — C21H30O2
⑰CARBON DIOXIDE — CO2

**Comment by csaboka** [comment]
This space is for reporting issues and improvement ideas for SpaceChem Community Edition. It's not meant to be a general forum for discussing the game. For those kinds of discussions, please use the SpaceChem subreddit at https://www.reddit.com/r/spacechem/ , the Steam community discussions at https://steamcommunity.com/app/92800/ , or the Unofficial Zachtronics Discord at https://discord.gg/nuTdGfN .

The SpaceChem rules aren't very suitable for building complex organic molecules like Penicillin. Squeezing something like that into even a 8x4 "large molecule" box won't work. You may want to take a look at Molek-Syntez, the latest Zachtronics game, which is about building such large molecules. (The rules are pretty different from SpaceChem, though.)
