### ISSUE TITLE
Allow research assignments to be saved to the toolbar and loaded back

### ISSUE THREAD

**Issue by csaboka** [spacechem-community-developers/SpaceChem-Community-Edition#2]
This is the only part remaining from [#32 of SpaceChemPatch](https://github.com/csaboka/spacechempatch/issues/32) that isn't implemented yet, so I've migrated it here for future tracking.

**Comment by csaboka** [comment]
@12345ieee : Now that it's possible to export and import research solutions, I can't see what good would it do to allow saving research reactors to the toolbar. Researches use different reactor types than productions, so you wouldn't ever be able to drop the saved reactor into a research level.

Do you think this is still something we should consider implementing, or can I close this issue?

**Comment by 12345ieee** [comment]
Yeah, I agree, this just duplicates now existing functionality, and does it worse.

I'll close it myself.
