### ISSUE TITLE
Can you version on main screen in welcome?

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#21]
Like the title what I hope.

**Comment by csaboka** [comment]
I'm sorry, I can't understand what you are trying to ask here. Please try to explain it in complete English sentences.

Also note that the Community Edition already shows its version number in the bottom right corner of the screen. If you have Steam overlays enabled, the overlay may initially cover it directly after starting the game, though.

**Comment by mikezang** [comment]
I am sorry that my poor English, I wanted to write “Can you show version in welcome message on main screen?”, but I posted before checking. 
By the way, I use SpaceChem on Mac, what do you mean Steam overlays enabled?

**Comment by csaboka** [comment]
Steam has this feature where it can show messages in front of the game you're playing. Normally it's just pop-up messages in the bottom right corner (messages from friends for example), but you can press Shift-Tab to open a big overlay with community content. When you start a game, it gives you a pop-up message telling you about the Shift-Tab shortcut, and that message can cover the version number, which also shows up in the bottom right corner.
