### ISSUE TITLE
Can you copy performance data for Multiple solution support

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#23]
This is very useful function what I like it!
But now it is easy to be used, there is no performance data after I copied so that I have to load then run again after rename, then load original to do next modify, i only need to rename if you can copy data, is this difficult?

**Comment by csaboka** [comment]
I'm not sure about this.

Copying your score when copying a solution would be easy. The score is supposed to be the one for your last successful run, and technically a freshly copied solution doesn't have a successful run yet. You could copy a solution that doesn't currently work but worked some time in the past, and it would get a misleading score.

I've also tried this with Exapunks, and it doesn't copy your score when you copy a solution. It shows it as unsolved until you run the copy. So it would make sense to keep this as it is now, and have it work the same way it does in other Zachtronics games.
