### ISSUE TITLE
Add Flip-Flop toggle for custom research and production

### ISSUE THREAD

**Issue by RandomPanda0** [spacechem-community-developers/SpaceChem-Community-Edition#25]
Currently, custom research and production puzzles always have flip flops available, which is not provided in much of the game's original campaign.  Adding the option to remove these introduces the possibility of making otherwise easy levels more challenging.

If this is possible, it'd also be interesting to be able to disable syncs and perhaps more, but let's just leave it at this for now.

**Comment by csaboka** [comment]
Is this what you had in mind?
![image](https://user-images.githubusercontent.com/2852084/83395447-95e22a00-a3fa-11ea-8dbf-1983e1558ac4.png)

I've arrived to the list of three instructions to enable/disable via elimination. Arrows, input and output instructions are required for a puzzle to be playable at all. Technically you could disable grab/drop and still move atoms via quantum tunnels, but that would make no sense in practice. You can disable bond, fuse, split, sense and swap instructions by removing the corresponding reactor features. This leaves rotate, sync and flip/flop as instructions that could be meaningfully toggled.
