### ISSUE TITLE
Add Bond+/Bond-/Quantum options for custom reactors

### ISSUE THREAD

**Issue by RandomPanda0** [spacechem-community-developers/SpaceChem-Community-Edition#26]
It is currently possible to make custom reactors contain any number of components, but it would be more feature complete to allow those custom reactors to be quantum, bond+ limited, or bond- limited reactors.  It probably requires more UI spaghetti, but it'd be great to have!

**Comment by csaboka** [comment]
Yeah, I think the hardest part of this one would be figuring out the UI. Also, it would technically be possible to have any combination of bond-, bond+ and "standard" bonders inside a reactor, so a more feature-complete approach would let you specify three numbers (regular bonders, remove-only bonders, add-only bonders). This would also complicate the UI, of course.

For the quantum boundary, I'm wondering how hard it would be to specify arbitrary wall shapes. The current code can only handle one vertical wall, but I'm not sure how useful it would be to toggle only that.

**Comment by csaboka** [comment]
I have implemented the bond+/bond- feature today. With the current implementation, you can specify three values: regular bond, bond+ and bond+, all three of them between 0 and 8 inclusive. This means that you can have a whopping 24 bonders in your reactor if you max out all three, although I can't see a puzzle where this would be practical to do. I expect some puzzles would specify a combination of the three to get some interesting effects, though.
