### ISSUE TITLE
Add proper mousewheel support

### ISSUE THREAD

**Issue by csaboka** [spacechem-community-developers/SpaceChem-Community-Edition#28]
SDL reports mouse wheel events to the game, but the game confuses them for left button events. It would be nice if the game recognized the wheel properly and handled it in an intuitive manner. Some ideas:
* The wheel should switch between pages in ResNet paged lists
* The wheel should switch between pages of the reactor toolbar
* Maybe even have the wheel cycle between variants of symbols (grab-drop/grab/drop, rotate CW/rotate CCW, input alpha/input beta etc) so you can enter programs with fewer clicks.

Other ideas are welcome in the comments.

**Comment by csaboka** [comment]
Basic wheel support is now available both in vanilla and in the CE. Instruction cycling isn't something I wanted to introduce while the tournament is running, so that feature will be available once the 2020 tournament is concluded.

**Comment by rexkix** [comment]
Make the mouse wheel scroll the page of solutions, either page by page (okay) or solution by solution (better).

**Comment by csaboka** [comment]
Everything else that's scrollable is scrolled page by page, so the solution picker will also do it page by page. This is to keep things consistent, and it's also easier to implement that way :)

**Comment by csaboka** [comment]
Now instruction cycling is also released, closing the issue now.
