### ISSUE TITLE
New Option: Replace or silence the annoying "reactor crashed" sound

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#31]
Create a new option to replace or silence the "reactor crashed" sound.  I have neighbors who complain way too easily and often about my game playing.  Hell, I find that sound super annoying even if that weren't the case.

**Comment by csaboka** [comment]
This makes sense. Silencing it completely is easy. For replacement, we can only work with the sound effects that already come with the game, so I'm not sure how much sense that would make.

**Comment by 12345ieee** [comment]
You don't need any change in the code for this (or to use the CE at all).

The game sounds are stored in `<bunch of steam folders>/SpaceChem/sounds`, the one you dislike I imagine is `sfx_fail.wav`.

Simply replace it with whatever you like.

**Comment by 12345ieee** [comment]
Closed, because it's solved by the manual sound editing of the previous comment.
