### ISSUE TITLE
Option to disable victory fanfare

### ISSUE THREAD

**Issue by csaboka** [spacechem-community-developers/SpaceChem-Community-Edition#32]
The victory fanfare sounds extremely satisfying when you first solve a level, but it gets annoying quickly when you're trying to optimize and it keeps interrupting the regular background music.

Add an option to disable it, or to limit it to play only when you first solve a puzzle, if that's not too difficult.

**Comment by 12345ieee** [comment]
No need for direct support, one can use the same workaround as https://github.com/spacechem-community-developers/SpaceChem-Community-Edition/issues/31#issuecomment-643782255 .
