### ISSUE TITLE
Crash when going from paused to simulation

### ISSUE THREAD

**Issue by G-Wen** [spacechem-community-developers/SpaceChem-Community-Edition#33]
Consistently crash the game by:
1. Load a solution (must not have run the solution after loading)
2. Press pause
3. Press any of the run simulation buttons

**Comment by csaboka** [comment]
The pause button shouldn't be enabled at all when the solution isn't running. This was a bug I introduced while working on the free-form production puzzles. It should be fixed in the next CE release.

Thank you for the bug report!
