### ISSUE TITLE
Allow users to make both waldo instructions invisible

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#35]
Sometimes I want to watch a ghost machine work, but you can only make the non-selected waldos instructions invisible.  Please consider relaxing that rule so that both waldos instructions can be made invisible.

**Comment by csaboka** [comment]
This will be released after the tournament as an option. When you hide the currently active layer, the instruction toolbar will be disabled as well, to prevent the already confusing situation from being even more confusing. (Without this, you would be able to drop instructions without seeing the result.)
