### ISSUE TITLE
Solution Name Textbox Crashes

### ISSUE THREAD

**Issue by brookie2664** [spacechem-community-developers/SpaceChem-Community-Edition#36]
I found that you can type `~` into the textbox and following it up with numbers allows you to input certain symbols:
```~00 = subscript 0
~01 = subscript 1
...
~09 = subscript 9
~10 = superscript +
~11 = superscript -
~12-34 = [?]
~35 = Venus symbol
~36 = Mars symbol
~37-63 = [?]
```

Typing any number 64 and above instantly crashes the game.

**Comment by csaboka** [comment]
Congratulations, you've found an issue with the original game! :)

This is something only meant to be used internally by the game, but it doesn't filter it from player-entered text. We'll see how complex it is to fix it without removing the ability to display these special symbols in other places.

**Comment by csaboka** [comment]
I could fix the crash part at least, so if you enter a value above 63, it will just show the entered characters as-is without crashing.

Making tildes work without this special behavior requires more consideration. The game needs these special sequences to show subscripts in molecule formulas, so disabling them completely is not an option. We would need a way to disable them only when displaying things that could have come from a player, as opposed to being baked in by a developer.

**Comment by csaboka** [comment]
This is fixed in the latest release.
