### ISSUE TITLE
Make instruction tool-tips not popup when simulation is running

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#37]
Apologies in advance.  This is super trivial and probably only bugs me.

The tool-tips for reactor objects (e.g. bonders, fusion lasers, etc.) do not show when a simulation is running but those for instructions do.  Often I'll accidentally move my mouse over the bottom of the screen when running a simulation and the instruction tool-tips pop up, blocking my view.  I can't think why I'd want them when running a reactor.

**Comment by csaboka** [comment]
I agree with you that this is inconsistent. None of the other tooltips show up while the simulation is running, so it makes sense not to show these, either.
