### ISSUE TITLE
Change the speed of Ctrl+<n> to be a factor instead of an absolute delta

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#38]
I just "discovered" the feature where you can select Ctrl+speed to increase the speed of the simulation.  I wanted to make a speed between 2 and 3, and picked a delta of 50.  With the default 1 speed being 2 and the default 2 speed being 10, this means that I'd have Ctrl+1 at 52 and Ctrl+2 at 60 for a barely noticeable difference between the two.  The speed of Ctrl+3 would be even less noticeably different from the speed of 3.

Wouldn't it be better to make the Ctrl+speed setting be a factor instead of an absolute delta?

I understand that this is probably a difficult change to accept, given that config files already exist and this would have to be an additional field in the file.  Both fields would have to be supported at the same time.  Yuck.

Sigh.  And maybe even this simple idea isn't right, though it would be better than using an absolute delta.  What I really want is Ctrl+1 to be some amount between 1's and 2's speed and Ctrl+2 to be some amount between 2's and 3's speed.  Making the factor be 5 wouldn't accomplish this goal either, as it would make the speed of Ctrl+1 be the same as the speed of 2.

I propose the following formula, though I'm not in love with it either.  I bet you can do better. Regardless, no matter what, unless it is a simple factor, it would be difficult to explain.
Speed<ctrl-n> = Speed<n> + (factor * (Speed<n+1> - Speed<n>))

**Comment by rexkix** [comment]
After thinking about this more, it would probably better would be to have four config file entries, one for each Ctrl+<n>.  That would provide most flexibility without having to rely on some mysterious formula.  If set to a non-zero value, these would override the delta.

**Comment by 12345ieee** [comment]
The reason it is like this is because it emulates a feature of the old SCP where Ctrl+<any button> went at infinite speed and the rest of the speeds were unchanged.

I use the fields as
```
speedSlow = 2
speedMedium = 5
speedFast = 15
speedFastDefense = 15
speedWarp = 400
speedWarpDefense = 200
speedDeltaCtrl = 32000
speedRecording = 8
```

and I effectively get back the behaviour of SC v1012 with SCP.

Newer zach games have even less speed options than SC has, I don't think we need even more, if you need a speed between 2 and 3 just make it 3, shift 3 into 4 and 4 into the delta, kinda like I did.

**Comment by 12345ieee** [comment]
I'm closing this because I don't see a compelling reason to add more speed options.

Feel free to comment here and we'll reevaluate it.
