### ISSUE TITLE
Remove confirmation of exiting the level when pressing escape

### ISSUE THREAD

**Issue by Darayavaush** [spacechem-community-developers/SpaceChem-Community-Edition#39]
The game doesn't warn you when you close it altogether, so it seems kinda odd to have a warning on a mere level exit.

**Comment by csaboka** [comment]
Hmm, this is weird. Our original assumption was that the game only asks for confirmation when you're trying to exit a running level. In fact, it always asks for confirmation when you exit by pressing Escape, and it asks for confirmation when you use the mouse _and_ the level is running.

I think I'll just change the existing option to suppress the confirmation prompt all the time. People who enable this option probably don't want the prompt at all, and it's not like you lose any part of your solution when you exit a level.

**Comment by csaboka** [comment]
This will be updated in the next CE release.
