### ISSUE TITLE
Add an option to overwrite the arrow/command on the field when trying to put a new one there

### ISSUE THREAD

**Issue by Darayavaush** [spacechem-community-developers/SpaceChem-Community-Edition#41]
Currently, if you have an arrow and you want to make it point another way, you have to either:
1. right-click on it and choose the correct direction;
2. right-click on it, select 'delete' and place a new one;
3. or select it and press delete on your keyboard.

All of those actions are very slow. I would like to have an option to just be able to slap a new arrow pointing the correct way on top and have it automatically overwrite the previous one.

**Comment by csaboka** [comment]
This will be included in the next CE release as a new option.
