### ISSUE TITLE
Allow to do group drags/rotations/reflections of commands together with glyphs

### ISSUE THREAD

**Issue by Darayavaush** [spacechem-community-developers/SpaceChem-Community-Edition#43]
Right now it's only possible to do group drags of commands only, which is quite limiting.

**Comment by csaboka** [comment]
The current code base doesn't even have the concept of a selected reactor feature, they are only moved one by one. I doubt there are proper graphics available to indicate a selected feature.

Rotating or mirroring a multi-tile feature is also impossible. There are no vertical or (horizontally) mirrored versions of fusers and splitters, so they cannot be rotated or mirrored horizontally.

**Comment by Darayavaush** [comment]
Ah, true. I was only thinking about bonders and tunnels when I made this request (since we were in the middle of w3 and I had to drag and rotate the whole ten-glyph output assembly a number of times, which got old quite fast).

**Comment by Darayavaush** [comment]
So I take it this isn't happening?
