### ISSUE TITLE
Instead of prepending "Copy of" to solution when copying, append "(copy)"

### ISSUE THREAD

**Issue by Darayavaush** [spacechem-community-developers/SpaceChem-Community-Edition#44]
The actual name is the more interesting part, but with the current approach the visible part of any name turns into a useless "Copy of Copy of Copy of Cop..." after several copies. With this suggestion the user-given name will always be visible.

**Comment by andy75381** [comment]
I also waste a lot of time removing the "Copy of" prefixes but would like it to not change the name at all

**Comment by csaboka** [comment]
The next CE will append "(copy)" instead of prepending "Copy of". I understand some people don't want the name to change at all, but now that it's a suffix, it will be easier to get rid of the copy marker. I don't think this warrants an option.
