### ISSUE TITLE
Close the reaction error message with backtick (`)

### ISSUE THREAD

**Issue by Darayavaush** [spacechem-community-developers/SpaceChem-Community-Edition#46]
The logic is that in a production puzzle if you want to stop the reaction before the crash, you have to press ` (since escape exits the reactor), but if you want to stop it after the crash, you have to use escape, so the user doesn't have a consistent hotkey "cease this bs and lemme edit". I'd like to see more consistent behavior.

**Comment by csaboka** [comment]
This will be implemented in the next CE version.
