### ISSUE TITLE
Check the icon of custom reactors in CE productions

### ISSUE THREAD

**Issue by 12345ieee** [spacechem-community-developers/SpaceChem-Community-Edition#49]
The tooltip of a custom reactor has this icon:
![image](https://user-images.githubusercontent.com/4094351/87883058-f4905100-ca04-11ea-9801-69ea5c00f2c0.png)
that looks wrong, that's a drill icon, not a component icon.

Check where is comes from.

**Comment by csaboka** [comment]
This should be fixed in the next version.
