### ISSUE TITLE
Mouse wheel in a solution changes pages of puzzles

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#54]
If you're in a puzzle and use the mouse wheel and then exit the puzzle, you'll find the pages of puzzles has changed.
For instance open a puzzle in the journal, use the mouse wheel, then exit that puzzle.  You're now on a different page in the journal.
I'm betting this gets fixed when using the mouse wheel in a puzzle has meaning.

**Comment by csaboka** [comment]
This should be fixed in the next release.
