### ISSUE TITLE
Repeat Undo / Redo when holding Ctrl-Z or Ctrl-Y or holding the mouse button on Undo / Redo button

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#55]

**Comment by 12345ieee** [comment]
Repeating on holding Ctrl+Z/Y got into the game for free with the update to SDL2.

I'm not sure it's worthwhile to also do it on button held, normal programs don't behave like that.

**Comment by csaboka** [comment]
I agree that support for holding down the UI button isn't worth it. It would take a lot of code and it's indeed not intuitive.

I'm closing this. The repeated hotkey should be good enough if one needs to quickly undo a large amount of changes.
