### ISSUE TITLE
Bug: Empty default solution, but some non-default solutions.  Edit the puzzle.  Doesn't warn, but deletes solutions

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#58]
If you have an empty default solution, but some non-default solutions and edit a puzzle, the game doesn't warn.  It deletes the solutions.  You now have an empty solution named "0".

**Comment by csaboka** [comment]
Some context here: this is happening in free-form production puzzles. The game is supposed to erase all your solutions if you change anything on the terrain. If your default solution is empty, it assumes you don't have any solutions and skips the warning dialog.

**Comment by csaboka** [comment]
This should be fixed in the next release.

To keep the implementation simple, the warning _won't_ be shown if you have non-default solutions but all of them are empty. If you have such solutions, they will be just wiped without question.
