### ISSUE TITLE
Updates to Russian Translation

### ISSUE THREAD

**Issue by winterheart** [spacechem-community-developers/SpaceChem-Community-Edition#6]
Hello, can you please update Russian translation of SpaceChem?

[SpaceChem 1014 Russian translation.zip](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition/files/3269666/SpaceChem.1014.Russian.translation.zip)

**Comment by 12345ieee** [comment]
This has been around for a while, as it's the same translation of https://steamcommunity.com/sharedfiles/filedetails/?id=203201254 .

This cannot really be included in the CE, for technical reasons, but we're evaluating incorporating it in the main game.

We mostly need to find someone to review it, we'll let you know.

**Comment by winterheart** [comment]
Hello.
Yes, this translation made by me, based on current translation of SpaceChem.

**Comment by 12345ieee** [comment]
Ok, with the changes done in v6.0 and the direct Steam support, we can now incorporate this into the CE without also forcing it into mainline.

Can you check the translation is still accurate for v1016? If it is we'll add it.

**Comment by winterheart** [comment]
There no changes since 1014, so all OK from me.

**Comment by csaboka** [comment]
Your improved translation will be included in the next release of the Community Edition. Thank you for your patience!

**Comment by csaboka** [comment]
This has been released just now as part of the latest CE. I'm closing this now, but feel free to reopen if it needs further changes.
