### ISSUE TITLE
Add ability to use more than 3 profiles

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#60]
Each year, before and after the tournament, I still use SpaceChemTool to add and remove profiles.  I'd like my playing profile to be clean each year as well as my importing profile.  I gather I can rename files in my save files folder, but I don't know which files to rename or how that all works.  It would be easier if there was a way to deal with that directly in the game.

Barring that, could you please give me some kind of clue as to which files to manage and how to manage them.  Thanks.

**Comment by 12345ieee** [comment]
Get a sqlite DB client (e.g. https://sqlitebrowser.org/ ) and open the `.locals` file in the save directory.

The stuff you want is in the `User` table.

**Comment by csaboka** [comment]
This will be included in the next CE release.
