### ISSUE TITLE
Enhancement Request: Reduce size of level export codes by omitting redundant fields

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#68]
E.g. CE research levels include the new 'quantum walls' fields even if both are null. When the level code is re-created without these fields it is still accepted by SpaceChem's Import Puzzle. Removing non-enabled custom reactors would be nice too

The same could also be done for vanilla fields that are set to false, e.g. "has-fuser" etc., which can be removed without the game complaining on import.

The only downsides I see to removing these are: 
* convenience of people manually changing the JSON - but if they need to know what fields are available they can always use SC to create a sample level that has one of everything
* Old levels will have a different code when imported and then exported - I don't know of anyone relying on this sort of behavior to remain consistent. As long as including the redundant fields doesn't break import, ResearchNet probably doesn't care either
* SC's internal code for exports is a bit more complex - up to you if this is a big one

**Comment by 12345ieee** [comment]
There was a technical reason for this related to vanilla compatibility, but I don't remember the exact details.

@csaboka can fill in for sure.

**Comment by csaboka** [comment]
My goal is to get the exact same export files as vanilla whenever the level is compatible with vanilla, to ensure maximum backwards compatibility. (We have at least one tool beyond SpaceChem to worry about, [the online mission viewer](http://www.coranac.com/spacechem/mission-viewer), but there could be others I don't know about.) You are correct that always writing the two quantum fields goes against this, but this should be a simple fix. Removing the boolean fields like "has-fuser" would be against this, on the other hand.

Non-enabled custom reactors can still be placed on the level as fixed reactors, so blindly removing them won't work, and checking whether they're actually placed on the level would be just too much effort for little benefit.

In general, I don't see much value in shrinking exports by omitting fields. There is already a gzip step in there, which should deal with redundancy very well, and writing all fields (when backward compatibility is not a concern) keeps things nice and simple.

**Comment by csaboka** [comment]
I'm assigning this to myself only for the quantum field fix. I'm considering the rest "won't fix".
