### ISSUE TITLE
Add hotkeys for ResearchNet browsing screens

### ISSUE THREAD

**Issue by csaboka** [spacechem-community-developers/SpaceChem-Community-Edition#7]
Hotkey ideas so far:
- Arrow keys: move selection
- PgUp/PgDown: previous/next screen
- Delete: delete selected puzzle (only in custom assignments)
- Enter: play selection (maybe edit the selection for custom assignments)

**Comment by G-Wen** [comment]
Other ideas:
Enter/Escape for confirmation on delete level
Enter/Escape for confirmation on hacking into ResearchNet (or just remove this entirely)
Extend PgUp/PgDown for navigating between planets on the main page
WASD / Arrow keys for selection of custom assignments

**Comment by csaboka** [comment]
I've added this to source control, it will be part of the next release.

The Delete confirmation box already allowed Enter to confirm and Esc to cancel, so I didn't touch it. The level selector already allows switching between planets with Left/Right and A/D, but now it will also allow PgUp/PgDn.
