### ISSUE TITLE
The saved multiple solutions?

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#75]
I use the newest v6.3.1 to instead of v5.1, but I found all my multiple solutions saved are not there, how can I restore all my solutions?

**Comment by csaboka** [comment]
I have no idea. You are the first person to report an issue like this. If you're sure that it isn't some kind of mixup with your save files, you can try sending me your save file and I can try investigating what may be going wrong here.

Your save file lives at "c:\Users\<your username>\AppData\Local\Zachtronics Industries\SpaceChem\save" on Windows. On other OSes, I don't know the location by heart, but it should still be in a folder named "SpaceChem" somewhere inside your user profile folder. The save file are those whose name end with ".user".

**Comment by mikezang** [comment]
Here is my saved game file, but I am not sure if it is original files before I played v6.3.1.
[Archive.zip](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition/files/6067298/Archive.zip)

**Comment by csaboka** [comment]
Your largest save file, 000.user, contains extra solutions and I can load them just fine with the latest version:
![image](https://user-images.githubusercontent.com/2852084/109702532-a5aeba80-7b94-11eb-9b65-9f6d37959c06.png)
![image](https://user-images.githubusercontent.com/2852084/109702554-ab0c0500-7b94-11eb-859f-2c7a44e8312a.png)
![image](https://user-images.githubusercontent.com/2852084/109702562-ae9f8c00-7b94-11eb-93ab-0f3d5fa247e1.png)

Are you sure you're playing with the right profile? The other two files have no extra solutions.

**Comment by mikezang** [comment]
Can you tell me which profile name of that saved game?

**Comment by mikezang** [comment]
I tried to load all four saved game profiles, there is no what you viewed original multiple solutions. 
By the way, I am using Mac El Capitan 10.11.6, I am not sure if this is the problem...

**Comment by mikezang** [comment]
Sorry that I did mistake, I got my multiple solutions, thanks a lot.
