### ISSUE TITLE
Can you provide input by specific sequence?

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#76]
I want to know if you can provide to create specific sequence input, so we can test our route.
For example, I can define O1-O2-O3, O1-O2-N1, O1-N1-O2, N1-O1-O2,... and so on.

**Comment by csaboka** [comment]
On a free-form production puzzle, you can place a programmed input and define the sequence you want. You can do the same in sandbox puzzles. Other than those two options, you can't specify the sequence in which inputs are generated.
