### ISSUE TITLE
Can you provide real random input sequence?

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#78]
Random is created by seed, if you use current timestamp as seed, you can provide real random sequence, is it possible?

**Comment by 12345ieee** [comment]
This is technically possible of course, but won't be implemented.

Different runs of the same level must be comparable to each other and deterministic as spacechem has no mechanism to allow randomness not to interfere with the final score.

You can change the random seed of inputs in CE-only productions, but each seed has to be a different puzzle.

**Comment by mikezang** [comment]
How can I change random seed in CE?

**Comment by csaboka** [comment]
You create a new free-form production puzzle, place a random input on the terrain, then double-click on it to edit it. The same screen that allows you to specify the output molecules also allows you to specify the random seed.
