### ISSUE TITLE
Newer .NET?

### ISSUE THREAD

**Issue by richard-gravy** [spacechem-community-developers/SpaceChem-Community-Edition#91]
Hello,
I'm not sure how complicated it would be for this to convert from .NET Framework to .NET Core, but I did notice the large window that appears on a vanilla Windows 10 install when launching the game, asking/requiring to install .NET Framework when nothing else seems to need it.

This would likely affect Linux/MacOS support, but apparently Microsoft is providing direct support for those platforms.

**Comment by 12345ieee** [comment]
This is something that needs to be brought up to Zachtronics directly, if there is really a need for it.

If you can make a convincing business case, send an email to zach@zachtronics.com .
