### ISSUE TITLE
[Bug] Random input seeds failing to edit

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#95]
Reproduction steps:
import this custom puzzle into SC:
```
H4sIACT9PGEA/+1VPW/bMBD9KwZnE5Aop0mlqegQj0HQrQgCWqQtAvxQyWMcIXB/e4+UHFtxlg
IZPQn37vO9o8g34rkVzlBl+wi0daZ3VloIpP79RozTso1azi1Sk3unRfMjNqy8/V4UZElaFy2Q
+tthOYt70ByUjaZ5gBR7N499Wh67BykFqcsl6b0TsQXlLBVS8wHBYklchDRdr/o8CiGYCUOfOg
jPd5T7jQLP/TDSwB6vuRqm36QuWHXnuTFSfMbz6b3BB/oTCtzvJA48Y7YeBBaVtln/LVjDits7
VjRVgXKwpkgWa0q0EsgyyKpsFdOnHCMZaoKR1ZheZquq5kKtisOcbjBca3om1TRhps2qzJtl3j
wECp13cdfRXE36ifGJKt0r6OjIdVIDOukvNMKebo8KeslbcJ6mifI2xhWEIM1GD0c3DpNxocKF
C4sZ/no0sQaOjJN5rmxeWxsD4KE4+XEXlpvE/2d2LR5H16LENrzvJcdz1Ca/e5F+77wWz1P2c0
BxsDgGdjzQjQM4nnZSg49yhh9VGB0bZ0UWIq+heAd6HcMlavCgn8NB2uDOs7cxzKqFXiuAGQRS
y975OZgknLRXNuBoeenTVv5EbiEauseQQHH/Nmr9ER5GOP2cn+vIrjp+iY7VVccv0XF11fF/dD
w9h2ePAt7fJloFA5VCJQSlmtT+db9epCd3vD8jdHgp16Rk1epGSSnT3a22W4VPHWCL6vAPDpwv
UyYIAAA=
```

Try to change the input component's random seed to 1 via the puzzle editor GUI, and save the puzzle.
Running solutions still use seed 0, and going back into the terrain editor for the level reveals the seed is indeed still 0.

**Comment by csaboka** [comment]
Well, this was a silly mistake on my part, one part of the code just forgot to load the random seed from the puzzle. I've pushed the fix to source control.

Given the lack of activity on this project lately, I don't expect a lot of other changes. This change will probably be released on its own as a bugfix release.

**Comment by csaboka** [comment]
This has been released on Steam this morning. Closing the issue.
