### ISSUE TITLE
can I run SpaceChem in 32bit Linux system?

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#96]
I am using a 32bit ThinkPad with AntiX 32bit linux system, can I run SpaceChem on it?

**Comment by csaboka** [comment]
I honestly have no idea, but you are welcome to try and let us know the results. I don't use Linux much, so I can't help you with setting it up.

**Comment by 12345ieee** [comment]
The game is compiled in x86 compatible mode for all OSes, so it should.

But in general, if vanilla runs, the CE will run, testing vanilla is just a matter of downloading it via steam.

**Comment by mikezang** [comment]
I use command as below to download SpaceChem,
steamcmd +force_install_dir ~/SpaceChem +login MySteamId +app_update 92800 -validate linux32 +quit
what can I download vanilla version?
