### ISSUE TITLE
about Steam macOS 10.11 and 10.12 Support

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#97]
It is said the Steam will stop to support macOS 10.11 ("El Capitan") in September, my old mac mini is still macOS 10.11, can I continue to use SpaceChem after September?

https://help.steampowered.com/en/faqs/view/0972-74BD-D8DE-662ESteam macOS 10.11 and 10.12 Support

**Comment by 12345ieee** [comment]
This you need to ask to the official support.
